### ISSUE TITLE
Experiencing lag in the console of noit and stratcon 

### ISSUE THREAD

**Issue by vrou** [circonus-labs/reconnoiter#223]
On another note, I have been experiencing some lag in the noit and stratcon consoles for some time now, but havn't had the time to create a issue before today..

I have just tested it on 2 different Ubuntu 14.04 systems, and both appear to have the same lag, when working inside the console.

When I type a character, it first appears on the console command line, when the next character have been typed in, and the whole "typing" is experienced to be slow.

Any ideas?

**Comment by postwait** [comment]
I've not seen this before.

**Comment by vrou** [comment]
Not an issue after all, swappiness was the culprit.
