### ISSUE TITLE
Scheduling issue(s)

### ISSUE THREAD

**Issue by daufderheide** [circonus-labs/reconnoiter#269]
I implemented my own DNS probe (based on the libudns one) and have found some issues with scheduling that I cannot explain.  Things seem fine when I only run a measurement or two, but when I setup say 10-15 probes per second (still not a lot) things start going nuts).  

First thing I see is that a probe that should fire every 10 seconds is firing sporadically.  Here's the first two times one particular measurement runs.  The first message is right after I set the NP_RUNNING flag and the second is shortly after that in the dns_check_send call

```
2016-06-23 15:48:35.070069] [debug/amaas_dns] recdns-soa_1 is running...
[2016-06-23 15:48:35.070104] [debug/amaas_dns] dns_check_send called
...
[2016-06-23 15:48:58.700329] [debug/amaas_dns] recdns-soa_1 is running...
[2016-06-23 15:48:58.700354] [debug/amaas_dns] dns_check_send called
```

You can see by the time stamps the second run was about 17 seconds after the first run.  Not even close to when it should have run.

I also see a lot of these errors in the noitd log:
`[2016-06-23 15:48:51.140765] [error] ctld-chnull_50 might not finish in 312ms (timeout 2000ms)`
That particular measurement returned and reported a 15 ms latency, but the log for it clearing the NP_RUNNING flag came very late (again according to time stamps)
```
[2016-06-23 15:49:02.213172] [debug] ctld-chnull_50 <- [latency_us: 15796]
[2016-06-23 15:49:02.213178] [debug] ctld-chnull_50 -> [available:good]
[2016-06-23 15:49:02.213460] [debug/amaas_dns] ctld-chnull_50 is no longer running...
```

Next, unlike the libudns dns probe, my probe does not implement timeout functionality.  Instead I'm using the same code from libudns to register the timeout with the eventer.  I'm relying on it to tell me when the measurement has timed out.  My current configuration has all timeouts set to 2 seconds, and for the most part its triggered the instant the timeout is reached.  However I've seen it take 6+ seconds and on occasion 10+ seconds to trigger the callback.  When it takes more than 10 seconds, the next measurement doesn't fire because NP_RUNNING is still set on it and the BAIL_ON_RUNNING macro fails it out.  Here's my eventer registration:
```
    newe = eventer_alloc();
    newe->mask = EVENTER_TIMER;
    gettimeofday(&now, NULL);
    p_int.tv_sec = check->timeout / 1000;
    p_int.tv_usec = (check->timeout % 1000) * 1000;
    add_timeval(now, p_int, &newe->whence);
    newe->closure = ci;
    newe->callback = dns_module_check_timeout;
    ci->timeout_event = newe;
    eventer_add(newe);
```

Last, if I leave this setup run long enough (about 15 measurements per second) triggering the above errors occasionally/fairly frequently) eventually all my probes get scheduled in negative time.  Using the cli "show check" both the last run and next run are negative and the next run is becoming a larger and larger negative number.  When this happens, noitd continues to run, but no measurements are sent.

Any help with this would be greatly appreciated.
-Dave

**Comment by postwait** [comment]
If this the only check in your system?  If the system is mostly idle it sounds like you might have something blocking in one of the callbacks.  There is rather heavy dtrace instrumentation around all of this stuff making it easy to ask questions about what it is doing while live.  Have you tried those?

**Comment by daufderheide** [comment]
It is the only check currently running in this latest example, however we can also get it with a lua check we wrote.  The C implementation of the DNS probe is single threaded and event driven based off the noitd eventer.  So we get callbacks for sending the check, when there's data on the file descriptor, and if/when it times out.  I can see the calls into my code all returning (based on logs).

It's very possible there's more than one problem happening here, but when the check goes to negatively scheduled time I can see from debug logs noitd is still running, and the cli shows the next scheduled time of the probe to be a larger and larger negative number which means it won't fire until it wraps around...  which will basically never happen.

**Comment by postwait** [comment]
The DTrace documentation is available at dtrace.org.  The probes available in the system are libmtev* and noit* provider probes and can be listed and interrogated via dtrace itself.

Additionally, there is the "show eventer debug timers" via the console.  That will list timers.  There should be no way for a timed event to have past and not be immediately picked up on the next event loop iteration unless the event isn't actually scheduled.

**Comment by daufderheide** [comment]
Sorry for the slow response, I have confirmed that there is a deadlock caused by my TCP DNS probe implementation.  I'm still working on a fix.  Once done I'll revisit the other problems we're seeing. Thanks for the debug advice...  Is there a better place to get help on issues?  Clearly this was NOT an issue with reconnoiter and it doesn't feel right opening tickets here to get help on what could easily be our issues.

-Dave
