### ISSUE TITLE
configure: error: circllhist.h not found

### ISSUE THREAD

**Issue by yogaredhat** [circonus-labs/reconnoiter#327]
I tried to install reconniter and found that its require libmtev. In order to  install libmtev , I installed libck,libjlog,luagit and fq. after that it complained about configure: error: *** libcircmetrics is required ***. so i tried to install it from https://github.com/yogaredhat/libcircmetrics/tree/master/src. And now got error that 'configure: error: circllhist.h not found'

http://pastebin.com/sQBD50nD

**Comment by postwait** [comment]
libcircmetrics requires https://github.com/circonus-labs/libcircllhist
