### ISSUE TITLE
configure: error: *** can't build zipkin-fq, no -lfq ***

### ISSUE THREAD

**Issue by yogaredhat** [circonus-labs/reconnoiter#328]
[root@localhost fq]# make
- compiling fqd_config.c
  fqd_config.c:33:21: fatal error: sqlite3.h: No such file or directory
  #include <sqlite3.h>
                     ^
  compilation terminated.
  make: **\* [fqd_config.o] Error 1

**Comment by postwait** [comment]
likely should be on the fq project... but it looks like it it needs the sqlite3 libraries and development headers.

**Comment by yogaredhat** [comment]
thank you for this update
i installed sqllite 3 and then i got the following error while running make on libmtev

- compiling luamtev.c
- linking luamtev
(cd modules && make)
make[2]: Entering directory `/usr/local/src/libmtev/src/modules'
- compiling zipkin_fq.c
- linking zipkin_fq.so
- compiling mtev_fq.c
- linking fq.so
lua.c: In function ‘mtev_lua_traceback’:
lua.c:484:3: error: implicit declaration of function ‘luaL_traceback’ [-Werror=implicit-function-declaration]+++++++
   luaL_traceback(L, L, lua_tostring(L, -1), 1);
   ^
cc1: all warnings being treated as errors
make[2]: *** [lua.lo] Error 1
make[2]: Leaving directory `/usr/local/src/libmtev/src/modules'
make[1]: *** [build-modules] Error 2
make[1]: Leaving directory `/usr/local/src/libmtev/src'
make: *** [all] Error 2

**Comment by postwait** [comment]
If you want to build lua support, luajit 2.0.3 or higher is required.

**Comment by yogaredhat** [comment]
installed  lua-5.1.4  and  LuaJIT-2.0.4 but got the same error

**Comment by postwait** [comment]
lua 5.1.4 is unneeded.  It sounds like you need to tell the build where to find the headers/libraries using CPPFLAGS and LDFLAGS overrides.

**Comment by yogaredhat** [comment]
I am not sure about how to use CPPFLAGS and LDFLAGS . I am using centos 7 . Can you provide any example about how to use these flags in centos.

Thanks

**Comment by yogaredhat** [comment]
execute following command and 'configure' step completed successfully  but still got the same error during make. . here is the error logs :http://pastebin.com/zu2b7NtB

Thanks

**Comment by postwait** [comment]
It looks to be picking up the lua headers instead of the luajit headers.  Make sure the -I in your CPPFLAGS specifies the luajit include dir before anything else.
