### ISSUE TITLE
Want M-only output from noit_b2sm

### ISSUE THREAD

**Issue by esproul** [circonus-labs/reconnoiter#445]
In the context of building a replay tool for raw log records, it would be helpful if one could request _only_ M records from `noit_b2sm`, since status/state-change records are not useful for metric replay. This would eliminate a second filtering step on the output of `noit_b2sm`.

I suppose there might be a case for S-only too, though I don't anticipate needing it.

**Comment by postwait** [comment]
Is there a strong reason not to not just `| grep '^M'` ? The tool is already UNIXy.

**Comment by esproul** [comment]
I suppose not. Closing as unnecessary.
