### ISSUE TITLE
support a tagset in the check configuration that will augment metric names

### ISSUE THREAD

**Issue by rileyberton** [circonus-labs/reconnoiter#461]
the `<check>` configuration should support a new `<tagset>` field.  The contents of this field
should be a validated set of stream tags (see noit_metric.h) and if there is a `<tagset>` field present on the check it means that all incoming metrics for the check have these additional `<tagset>` tags added to the metric name as stream tags.

If a check has `<tagset>a:b,c:d,foo:bar</tagset>` and a metric arrives on this check called `quux` the name should be transformed to: `quux|ST[a:b,c:d,foo:bar]`.  If a metric arrives on this check called 'baz|ST[region:us-east-1]`, the name should be transformed to: `baz|ST[a:b,c:d,foo:bar,region:us-east-1]`.  If a metric arrives that has the name `blarg|ST[a:b]`, the new name should be: `blarg|ST[a:b,c:d,foo:bar]` (by the tag property that there are no duplicate tags in a name).

**Comment by postwait** [comment]
I implemented it as `<tagset>|ST[a:b,c:d,foo:bar]</tagset>`
